# Generated by Django 5.0.6 on 2024-06-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=10)),
                ('coin', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
        ),
    ]
