# Generated by Django 5.0.6 on 2024-06-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='signal',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='signal',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='signal',
            name='timestamp',
            field=models.TextField(),
        ),
    ]
