# Generated by Django 5.0.6 on 2024-06-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_alter_signal_amount_alter_signal_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='signal',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='balance',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='signal',
            table='signals',
        ),
    ]
